sudo: required
services:
  - docker

before_install:
  - docker build -t pradeepp28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pradeepp28/react-test npm run test -- --coverage

after_success:
  - docker build -t pradeepp28/multi-client ./client
  - docker build -t pradeepp28/multi-nginx ./nginx
  - docker build -t pradeepp28/multi-server ./server
  - docker build -t pradeepp28/multi-worker ./worker
  #login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #now push the images
  - docker push pradeepp28/multi-client
  - docker push pradeepp28/multi-nginx
  - docker push pradeepp28/multi-server
  - docker push pradeepp28/multi-worker